// <auto-generated />
namespace ShootingStars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TweaksOnModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TweaksOnModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202105021215127_TweaksOnModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
